-- resultat_tourT1_creation.sql

CREATE TABLE resultat_tourT1 (
    "Code du département" VARCHAR(10),
    "Libellé du département" VARCHAR(255),
    "Etat saisie" VARCHAR(255),
    "Inscrits" INTEGER,
    "Abstentions" INTEGER,
    "% Abs/Ins" INTEGER,
    "Votants" INTEGER,
    "% Vot/Ins" INTEGER,
    "Blancs" INTEGER,
    "% Blancs/Ins" INTEGER,
    "% Blancs/Vot" INTEGER,
    "Nuls" INTEGER,
    "% Nuls/Ins" INTEGER,
    "% Nuls/Vot" INTEGER,
    "Exprimés" INTEGER,
    "% Exp/Ins" INTEGER,
    "% Exp/Vot" INTEGER,
    "Sexe" VARCHAR(255),
    "Nom" VARCHAR(255),
    "Prénom" VARCHAR(255),
    "Voix" INTEGER,
    "% Voix/Ins" INTEGER,
    "% Voix/Exp" INTEGER,
    "Sexe_1" VARCHAR(255),
    "Nom_1" VARCHAR(255),
    "Prénom_1" VARCHAR(255),
    "Voix_1" INTEGER,
    "% Voix/Ins_1" INTEGER,
    "% Voix/Exp_1" INTEGER,
    "Sexe_2" VARCHAR(255),
    "Nom_2" VARCHAR(255),
    "Prénom_2" VARCHAR(255),
    "Voix_2" INTEGER,
    "% Voix/Ins_2" INTEGER,
    "% Voix/Exp_2" INTEGER,
    "Sexe_3" VARCHAR(255),
    "Nom_3" VARCHAR(255),
    "Prénom_3" VARCHAR(255),
    "Voix_3" INTEGER,
    "% Voix/Ins_3" INTEGER,
    "% Voix/Exp_3" INTEGER,
    "Sexe_4" VARCHAR(255),
    "Nom_4" VARCHAR(255),
    "Prénom_4" VARCHAR(255),
    "Voix_4" INTEGER,
    "% Voix/Ins_4" INTEGER,
    "% Voix/Exp_4" INTEGER,
    "Sexe_5" VARCHAR(255),
    "Nom_5" VARCHAR(255),
    "Prénom_5" VARCHAR(255),
    "Voix_5" INTEGER,
    "% Voix/Ins_5" INTEGER,
    "% Voix/Exp_5" INTEGER,
    "Sexe_6" VARCHAR(255),
    "Nom_6" VARCHAR(255),
    "Prénom_6" VARCHAR(255),
    "Voix_6" INTEGER,
    "% Voix/Ins_6" INTEGER,
    "% Voix/Exp_6" INTEGER,
    "Sexe_7" VARCHAR(255),
    "Nom_7" VARCHAR(255),
    "Prénom_7" VARCHAR(255),
    "Voix_7" INTEGER,
    "% Voix/Ins_7" INTEGER,
    "% Voix/Exp_7" INTEGER,
    "Sexe_8" VARCHAR(255),
    "Nom_8" VARCHAR(255),
    "Prénom_8" VARCHAR(255),
    "Voix_8" INTEGER,
    "% Voix/Ins_8" INTEGER,
    "% Voix/Exp_8" INTEGER,
    "Sexe_9" VARCHAR(255),
    "Nom_9" VARCHAR(255),
    "Prénom_9" VARCHAR(255),
    "Voix_9" INTEGER,
    "% Voix/Ins_9" INTEGER,
    "% Voix/Exp_9" INTEGER,
    "Sexe_10" VARCHAR(255),
    "Nom_10" VARCHAR(255),
    "Prénom_10" VARCHAR(255),
    "Voix_10" INTEGER,
    "% Voix/Ins_10" INTEGER,
    "% Voix/Exp_10" INTEGER,
    "Sexe_11" VARCHAR(255),
    "Nom_11" VARCHAR(255),
    "Prénom_11" VARCHAR(255),
    "Voix_11" INTEGER,
    "% Voix/Ins_11" INTEGER,
    "% Voix/Exp_11" INTEGER
);